---
listeners:
  default:
    type: tcp
    bind: 127.0.0.1:1883
  websocket:
    type: ws
    bind: 127.0.0.1:9001
plugins:
  amqtt.plugins.authentication.AnonymousAuthPlugin:
    allow_anonymous: true
  amqtt.plugins.sys.broker.BrokerSysPlugin:
    sys_interval: 20
